export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as DashboardPage } from './DashboardPage'
export { default as AddTaskPage } from './AddTaskPage'
export { default as EditTaskPage } from './EditTaskPage'